### ISSUE TITLE
＋ボタンは幅固定にする

### ISSUE THREAD

**Issue by tamago324** [tamago324/texteditor_htmlcssjs#6]
タブが多くなっても小さくならないようにすること

**Comment by tamago324** [comment]
`min-width`をつければいける！？

```css
.tab-item-add {
  width: 24px;
  max-width: 24px;
}
```
